#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CelpontVadaszcentrum.Resource", IsApplication=true)]

namespace CelpontVadaszcentrum
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int CategoriesList = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int CategoryNameTextView = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int ProductNameTextView = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int ProductPreviewList = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int ProductPriceTextView = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int catalogButton = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int discountsButton = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int emailTXT = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int imgProduct = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int mainLinearLayout = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int mainScrollView = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int newsButton = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int newsWebView = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int newsletterButton = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int responseTXT = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int submitEmailButton = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int txtDescription = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int txtPrice = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int txtProductName = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CategoriesListLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CategoryRowView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainMenuLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NewsLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NewsletterLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ProductDetailLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ProductPreviewListLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ProductPreviewRowView = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
