#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CelpontVadaszcentrum.Resource", IsApplication=true)]

namespace CelpontVadaszcentrum
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::CelpontVadaszcentrum.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::CelpontVadaszcentrum.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::CelpontVadaszcentrum.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::CelpontVadaszcentrum.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::CelpontVadaszcentrum.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::CelpontVadaszcentrum.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::CelpontVadaszcentrum.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::CelpontVadaszcentrum.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::CelpontVadaszcentrum.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::CelpontVadaszcentrum.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::CelpontVadaszcentrum.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::CelpontVadaszcentrum.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::CelpontVadaszcentrum.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::CelpontVadaszcentrum.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::CelpontVadaszcentrum.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::CelpontVadaszcentrum.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::CelpontVadaszcentrum.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::CelpontVadaszcentrum.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::CelpontVadaszcentrum.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::CelpontVadaszcentrum.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::CelpontVadaszcentrum.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::CelpontVadaszcentrum.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::CelpontVadaszcentrum.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::CelpontVadaszcentrum.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::CelpontVadaszcentrum.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_errorstatus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_successstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundedbg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roundedbgdark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int SplashBackground = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int CategoriesList = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CategoryNameTextView = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int NewsletterDescriptionTXT = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int NewsletterHeadlineTXT = 2131099661;
			
			// aapt resource value: 0x7f06001c
			public const int ProductNameTextView = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int ProductPreviewList = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int ProductPriceTextView = 2131099677;
			
			// aapt resource value: 0x7f060008
			public const int catalogButton = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int discountsButton = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int emailAdressTXT = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int emailTXT = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int imgProduct = 2131099669;
			
			// aapt resource value: 0x7f060005
			public const int loadingImage = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int loadingProgressBar = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int loadingProgressWheel = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int logoImageView = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int mainLinearLayout = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int mainScrollView = 2131099667;
			
			// aapt resource value: 0x7f06000a
			public const int newsButton = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int newsWebView = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int newsletterButton = 2131099659;
			
			// aapt resource value: 0x7f060016
			public const int numberOfImagesTXT = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int responseTXT = 2131099666;
			
			// aapt resource value: 0x7f06001a
			public const int selectedCategoryInPreviewTXT = 2131099674;
			
			// aapt resource value: 0x7f060000
			public const int selectedCategoryTXT = 2131099648;
			
			// aapt resource value: 0x7f060011
			public const int submitEmailButton = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int textViewStatus = 2131099652;
			
			// aapt resource value: 0x7f060019
			public const int txtDescription = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int txtPrice = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int txtProductName = 2131099671;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CategoriesListLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CategoryRowView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loading = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingimage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loadingprogress = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainMenuLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewsLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NewsletterLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ProductDetailLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ProductPreviewListLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ProductPreviewRowView = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
